- name: Configure Pushover notifications
  lucasheld.uptime_kuma.notification:
    api_url: "{{ uptime_kuma_url }}"
    api_token: "{{ uptime_kuma_api_token }}"
    name: "{{ item.name | default(omit) }}"
    id: "{{ item.id | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    isDefault: "{{ item.isDefault | default(omit) }}"
    type: pushover
    applyExisting: "{{ item.applyExisting | default(omit) }}"
    pushoveruserkey: "{{ item.pushoveruserkey | default(omit) }}"
    pushoverapptoken: "{{ item.pushoverapptoken | default(omit) }}"
    pushoversounds: "{{ item.pushoversounds | default(omit) }}"
    pushoverpriority: "{{ item.pushoverpriority | default(omit) }}"
    pushovertitle: "{{ item.pushovertitle | default(omit) }}"
    pushoverdevice: "{{ item.pushoverdevice | default(omit) }}"
  loop: "{{ uptime_kuma_notifications['pushover'] | default([]) }}"
  tags:
    - uptime_kuma

- name: Configure Slack notifications
  lucasheld.uptime_kuma.notification:
    api_url: "{{ uptime_kuma_url }}"
    api_token: "{{ uptime_kuma_api_token }}"
    name: "{{ item.name | default(omit) }}"
    id: "{{ item.id | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    isDefault: "{{ item.isDefault | default(omit) }}"
    applyExisting: "{{ item.applyExisting | default(omit) }}"
    type: slack
    slackbutton: "{{ item.slackbutton | default(omit) }}"
    slackchannel: "{{ item.slackchannel | default(omit) }}"
    slackusername: "{{ item.slackusername | default(omit) }}"
    slackiconemo: "{{ item.slackiconemo | default(omit) }}"
    slackwebhookURL: "{{ item.slackwebhookURL | default(omit) }}"
  loop: "{{ uptime_kuma_notifications['slack'] | default([]) }}"
  tags:
    - uptime_kuma

- name: Configure monitors
  lucasheld.uptime_kuma.monitor:
    api_url: "{{ uptime_kuma_url }}"
    api_token: "{{ uptime_kuma_api_token }}"
    name: "{{ item.name }}"
    id: "{{ item.id | default(omit) }}"
    type: "{{ item.type }}"
    state: "{{ item.state | default(omit) }}"
    interval: "{{ item.interval | default(omit) }}"
    retryInterval: "{{ item.retryInterval | default(omit) }}"
    resendInterval: "{{ item.resendInterval | default(omit) }}"
    maxretries: "{{ item.maxretries | default(omit) }}"
    upsideDown: "{{ item.upsideDown | default(omit) }}"
    notificationIDList: "{{ item.notificationIDList | default(omit) }}"
    notification_names: "{{ item.notification_names | default(omit) }}"
    url: "{{ item.url | default(omit) }}"
    expiryNotification: "{{ item.expiryNotification | default(omit) }}"
    ignoreTls: "{{ item.ignoreTls | default(omit) }}"
    maxredirects: "{{ item.maxredirects | default(omit) }}"
    accepted_statuscodes: "{{ item.accepted_statuscodes | default(omit) }}"
    proxyId: "{{ item.proxyId | default(omit) }}"
    proxy: "{{ item.proxy | default(omit) }}"
    method: "{{ item.method | default(omit) }}"
    body: "{{ item.body | default(omit) }}"
    headers: "{{ item.headers | default(omit) }}"
    authMethod: "{{ item.authMethod | default(omit) }}"
    basic_auth_user: "{{ item.basic_auth_user | default(omit) }}"
    basic_auth_pass: "{{ item.basic_auth_pass | default(omit) }}"
    authDomain: "{{ item.authDomain | default(omit) }}"
    authWorkstation: "{{ item.authWorkstation | default(omit) }}"
    keyword: "{{ item.keyword | default(omit) }}"
    hostname: "{{ item.hostname | default(omit) }}"
    grpcUrl: "{{ item.grpcUrl | default(omit) }}"
    grpcEnableTls: "{{ item.grpcEnableTls | default(omit) }}"
    grpcServiceName: "{{ item.grpcServiceName | default(omit) }}"
    grpcMethod: "{{ item.grpcMethod | default(omit) }}"
    grpcProtobuf: "{{ item.grpcProtobuf | default(omit) }}"
    grpcBody: "{{ item.grpcBody | default(omit) }}"
    grpcMetadata: "{{ item.grpcMetadata | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    dns_resolve_server: "{{ item.dns_resolve_server | default(omit) }}"
    dns_resolve_type: "{{ item.dns_resolve_type | default(omit) }}"
    mqttUsername: "{{ item.mqttUsername | default(omit) }}"
    mqttPassword: "{{ item.mqttPassword | default(omit) }}"
    mqttTopic: "{{ item.mqttTopic | default(omit) }}"
    mqttSuccessMessage: "{{ item.mqttSuccessMessage | default(omit) }}"
    databaseConnectionString: "{{ item.databaseConnectionString | default(omit) }}"
    databaseQuery: "{{ item.databaseQuery | default(omit) }}"
    docker_container: "{{ item.docker_container | default(omit) }}"
    docker_host: "{{ item.docker_host | default(omit) }}"
    docker_host_name: "{{ item.docker_host_name | default(omit) }}"
    radiusUsername: "{{ item.radiusUsername | default(omit) }}"
    radiusPassword: "{{ item.radiusPassword | default(omit) }}"
    radiusSecret: "{{ item.radiusSecret | default(omit) }}"
    radiusCalledStationId: "{{ item.radiusCalledStationId | default(omit) }}"
    radiusCallingStationId: "{{ item.radiusCallingStationId | default(omit) }}"
  loop: "{{ uptime_kuma_monitors }}"
  tags:
    - uptime_kuma

- name: Configure status pages
  lucasheld.uptime_kuma.status_page:
    api_url: "{{ uptime_kuma_url }}"
    api_token: "{{ uptime_kuma_api_token }}"
  loop: "{{ uptime_kuma_status_pages }}"
  tags:
    - uptime_kuma
