- name: Download scrutiny binary
  get_url:
    url: https://github.com/AnalogJ/scrutiny/releases/download/v{{ scrutiny_version }}/scrutiny-collector-metrics-{{ ansible_facts.system | lower }}-{{ _scrutiny_binary_arch[ansible_facts.architecture] }}
    dest: "{{ scrutiny_bin }}"
    owner: root
    group: root
    mode: '0755'
  tags:
    - scrutiny

- name: Create scrutiny service
  template:
    src: scrutiny.service.j2
    dest: /etc/systemd/system/scrutiny.service
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd
  tags:
    - scrutiny

- name: Create scrutiny timer
  template:
    src: scrutiny.timer.j2
    dest: /etc/systemd/system/scrutiny.timer
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd
  tags:
    - scrutiny
    - timers

- name: Start and enable scrutiny scan
  systemd:
    name: scrutiny.timer
    enabled: yes
    state: started
  tags:
    - scrutiny
    - timers
