- name: Install required packages
  action: "{{ ansible_facts.pkg_mgr }}"
  args:
    name: "{{ _borg_packages }}"
    state: present
  tags:
    - borg
    - packages

- name: Create virtual environment
  pip:
    name: "{{ borg_pip_packages }}"
    virtualenv_command: "{{ borg_venv_python }} -m venv"
    virtualenv: "{{ borg_venv }}"
  tags:
    - borg
    - packages

- name: Link borg executable
  file:
    state: link
    src: "{{ borg_venv }}/bin/borg"
    dest: /usr/local/bin/borg
    owner: root
    group: root
  tags:
    - borg
