- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.system_vendor }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
      paths:
        - vars
  tags:
    - borg
    - always

- name: Include install tasks
  include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - install-{{ ansible_facts.system_vendor }}.yml
        - install.yml
      paths:
        - tasks
  tags:
    - borg
    - packages
  #   - always
